# version: "3.9"
services:
  backend:
    build: ./backend_new
    container_name: backend_new
    ports:
      - "4001:4001"   # host:container
    env_file:
      - ./backend_new/.env
      # - DB_HOST=doohgle.covkowi4e8h9.us-east-1.rds.amazonaws.com
      # - DB_PORT=5432
      # - DB_USER=Shiv
      # - DB_PASSWORD=Sada_8324
      # - DB_NAME=doohgle_db
      # - NODE_ENV=production
      # - PORT=4001
      # - PGSSLMODE=require
    networks:
      - app-network

  frontend:
    build: ./frontend_new
    container_name: frontend_new
    ports:
      - "3000:80"     # host:container
    environment:
      - VITE_API_URL=http://backend_new:4001
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
