services:
  - type: web
    name: backend
    env: node
    region: singapore
    plan: free
    rootDir: ./backend_new
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DB_HOST
        value: doohgle.covkowi4e8h9.us-east-1.rds.amazonaws.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: Shiv
      - key: DB_PASSWORD
        value: Sada_8324
      - key: DB_NAME
        value: doohgle_db
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
      - key: PGSSLMODE
        value: require
      - key: JWT_SECRET
        value: Sada_8324
      - key: AWS_ACCESS_KEY_ID
        value: AKIA46HVBEZPIIHK62PE
      - key: AWS_SECRET_ACCESS_KEY
        value: 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
      - key: AWS_REGION
        value: ap-southeast-2
      - key: S3_BUCKET_NAME
        value: doohgle
      - key: EMAIL_USER
        value: devlop8324@gmail.com
      - key: EMAIL_PASS
        value: Sada@8324
      - key: EMAIL_TLS_INSECURE
        value: true
      - key: GOOGLE_MAPS_API_KEY
        value: AIzaSyC4iDxiFxsSsVvJ0R-WEFwCwCMQ5ow0ZZ8

  - type: web
    name: frontend
    env: static
    region: singapore
    plan: free
    rootDir: ./frontend_new
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://backend-[your-render-service-id].onrender.com
