-- Insert sample campaign requests for testing
INSERT INTO campaign_requests (
  advertiser_id,
  venue_owner_id, 
  screen_id,
  campaign_name,
  campaign_description,
  start_date,
  end_date,
  requested_hours,
  budget_offered,
  creative_assets,
  target_audience,
  notes,
  status
) VALUES 
(
  (SELECT id FROM users WHERE role = 'advertiser' LIMIT 1),
  (SELECT id FROM users WHERE role = 'venue_owner' LIMIT 1),
  (SELECT id FROM screens LIMIT 1),
  'Summer Fashion Campaign',
  'Promote our new summer collection with vibrant visuals and catchy slogans',
  '2024-12-01',
  '2024-12-31',
  ARRAY[9, 10, 11, 18, 19, 20],
  25000,
  '[]'::jsonb,
  'Young adults aged 18-35, fashion conscious',
  'Looking for high-visibility locations with good foot traffic',
  'pending'
),
(
  (SELECT id FROM users WHERE role = 'advertiser' LIMIT 1),
  (SELECT id FROM users WHERE role = 'venue_owner' LIMIT 1),
  (SELECT id FROM screens ORDER BY id LIMIT 1 OFFSET 1),
  'Tech Product Launch',
  'Launch campaign for our innovative new smartphone with cutting-edge features',
  '2024-12-15',
  '2025-01-15',
  ARRAY[8, 9, 17, 18, 19, 20, 21],
  45000,
  '[]'::jsonb,
  'Tech enthusiasts, professionals aged 25-45',
  'Need screens in business districts and tech hubs',
  'pending'
),
(
  (SELECT id FROM users WHERE role = 'advertiser' LIMIT 1),
  (SELECT id FROM users WHERE role = 'venue_owner' LIMIT 1),
  (SELECT id FROM screens ORDER BY id LIMIT 1 OFFSET 2),
  'Holiday Sale Promotion',
  'End of year mega sale with up to 70% discounts on electronics',
  '2024-12-20',
  '2024-12-31',
  ARRAY[10, 11, 12, 16, 17, 18, 19, 20],
  30000,
  '[]'::jsonb,
  'Shoppers, families, deal seekers',
  'High foot traffic areas, shopping centers preferred',
  'approved'
),
(
  (SELECT id FROM users WHERE role = 'advertiser' LIMIT 1),
  (SELECT id FROM users WHERE role = 'venue_owner' LIMIT 1),
  (SELECT id FROM screens ORDER BY id LIMIT 1 OFFSET 3),
  'Restaurant Grand Opening',
  'Grand opening of our new fine dining restaurant with special offers',
  '2024-12-10',
  '2024-12-20',
  ARRAY[17, 18, 19, 20, 21],
  15000,
  '[]'::jsonb,
  'Food enthusiasts, local residents',
  'Need screens near our location in downtown area',
  'rejected'
),
(
  (SELECT id FROM users WHERE role = 'advertiser' LIMIT 1),
  (SELECT id FROM users WHERE role = 'venue_owner' LIMIT 1),
  (SELECT id FROM screens ORDER BY id LIMIT 1 OFFSET 4),
  'Fitness Center Membership Drive',
  'New Year fitness resolutions campaign for gym memberships',
  '2025-01-01',
  '2025-01-31',
  ARRAY[6, 7, 8, 17, 18, 19],
  20000,
  '[]'::jsonb,
  'Health conscious individuals, New Year resolution makers',
  'Target areas with young professionals and students',
  'pending'
);
